name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Navigate to BlogApp.API directory for restoring, building, and testing
    - name: Restore dependencies
      run: dotnet restore
      working-directory: BlogApp.API

    - name: Build
      run: dotnet build --no-restore
      working-directory: BlogApp.API
      
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish
      working-directory: BlogApp.API

  deploy:
    runs-on: self-hosted  # Use a self-hosted runner (assumed to be Windows-based)
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to IIS via Web Deploy
      run: |
        echo "Deploying to IIS..."
        Invoke-Command -ComputerName ${{ secrets.IIS_SERVER }} -Credential (New-Object System.Management.Automation.PSCredential("${{ secrets.IIS_USERNAME }}", (ConvertTo-SecureString ${{ secrets.IIS_PASSWORD }} -AsPlainText -Force))) -ScriptBlock {
            Import-Module WebAdministration
            $publishPath = "C:\inetpub\wwwroot\BlogApp"  # Path on the server where the app will be deployed
            Remove-Item -Recurse -Force $publishPath # Remove existing files
            Copy-Item -Path ./publish/* -Destination $publishPath -Recurse
        }
