name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: BlogApp.API

    - name: Build
      run: dotnet build --no-restore
      working-directory: BlogApp.API

    - name: Publish
      run: dotnet publish --configuration Release --output ${{ github.workspace }}/publish
      working-directory: BlogApp.API

    - name: Verify publish directory
      run: |
        echo "Contents of publish directory:"
        ls -R ${{ github.workspace }}/publish

    - name: Upload published files
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download published app
      uses: actions/download-artifact@v3
      with:
        name: published-app
        path: ${{ github.workspace }}/published-app

    - name: Verify downloaded files
      run: dir "${{ github.workspace }}\published-app"

    - name: Deploy to IIS via PowerShell
      run: |
        echo "Deploying to IIS..."
        powershell -Command {
            $publishPath = "C:\inetpub\wwwroot\BlogApp"
            $publishSourcePath = "${env:GITHUB_WORKSPACE}\published-app"

            Write-Host "Publish Source Path: $publishSourcePath"
            Write-Host "Publishing to Path: $publishPath"

            if (-Not (Test-Path -Path $publishPath)) {
                New-Item -Path $publishPath -ItemType Directory
            } else {
                Remove-Item -Recurse -Force $publishPath\*
            }

            if (Test-Path -Path $publishSourcePath) {
                Get-ChildItem -Path $publishSourcePath | Write-Host
                Copy-Item -Path "$publishSourcePath\*" -Destination $publishPath -Recurse
            } else {
                Write-Error "Publish source path $publishSourcePath does not exist."
            }
        }
