name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Navigate to BlogApp.API directory for restoring, building, and testing
    - name: Restore dependencies
      run: dotnet restore
      working-directory: BlogApp.API

    - name: Build
      run: dotnet build --no-restore
      working-directory: BlogApp.API
      
    - name: Publish
      run: dotnet publish --configuration Release --output D:\publish
      working-directory: BlogApp.API

  deploy:
    runs-on: windows-latest  # Use GitHub's Windows runner
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to IIS via Web Deploy
      run: |
        echo "Deploying to IIS..."
        powershell -Command {
            $publishPath = "C:\inetpub\wwwroot\BlogApp"  # Path on the server where the app will be deployed
            Remove-Item -Recurse -Force $publishPath # Remove existing files
            Copy-Item -Path D:\publish/* -Destination $publishPath -Recurse
        }  

