name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: BlogApp.API

    - name: Build
      run: dotnet build --no-restore
      working-directory: BlogApp.API

    - name: Publish
      run: dotnet publish --configuration Release --output ${{ github.workspace }}/publish
      working-directory: BlogApp.API

  deploy:
    runs-on: windows-latest  # Use GitHub's Windows runner
    needs: build  # Ensure this job runs after the build job
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print directory contents
      run: |
        dir "${{ github.workspace }}\publish"

    - name: Deploy to IIS via PowerShell
      run: |
        echo "Deploying to IIS..."
        powershell -Command {
            $publishPath = "C:\inetpub\wwwroot\BlogApp"  # Path on the server where the app will be deployed
            $publishSourcePath = "${env:GITHUB_WORKSPACE}\publish"  # Path where the app is published

            # Print the contents of the source directory for debugging
            Write-Host "Publish Source Path: $publishSourcePath"
            Write-Host "Publishing to Path: $publishPath"

            # Ensure the target directory exists, if not create it
            if (-Not (Test-Path -Path $publishPath)) {
                New-Item -Path $publishPath -ItemType Directory
            } else {
                # If the directory exists, clear existing files
                Remove-Item -Recurse -Force $publishPath\*
            }

            # Ensure the source directory exists
            if (Test-Path -Path $publishSourcePath) {
                # Print contents for debugging
                Get-ChildItem -Path $publishSourcePath | Write-Host
                # Copy the new published files
                Copy-Item -Path "$publishSourcePath\*" -Destination $publishPath -Recurse
            } else {
                Write-Error "Publish source path $publishSourcePath does not exist."
            }
        }
